// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlnteymkngophxwiytcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsbnRleW1rbmdvcGh4d2l5dGN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NzAyOTcsImV4cCI6MjA2NzA0NjI5N30.2B1uDQgzBW90hlMtBCFgym22pJcHncegDJvt7BuAtgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});